# TENSORS
Tensors là một cấu trúc dữ liệu chuyên biệt rất giống với mảng và ma trận. Trong PyTorch, chúng tôi sử dụng các tensor để mã hóa các đầu vào và đầu ra của mô hình, cũng như các thông số của mô hình.

Tensors tương tự như NumPy’s ndarrays, ngoại trừ Tensors có thể chạy trên GPU hoặc các trình tăng tốc phần cứng khác. Trên thực tế, các tensor và mảng NumPy thường có thể chia sẻ cùng một bộ nhớ bên dưới, loại bỏ nhu cầu sao chép dữ liệu (xem [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)). Các tensor cũng được tối ưu hóa để tự động phân biệt (chúng ta sẽ xem thêm về điều đó sau trong phần [Autograd](https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html)). Nếu bạn đã quen với ndarrays, bạn sẽ có thể sử dụng ngay tại nhà với Tensor API. Nếu chưa thì cùng theo dõi nhé!

In [1]:
import torch
import numpy as np

## Khởi tạo Tensor
Tensor có thể được khởi tạo bằng nhiều cách khác nhau. Hãy xem các ví dụ sau:
### Trực tiếp từ data
Tensor có thể được tạo trực tiếp từ data. Kiểu dữ liệu được suy ra tự động.

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

### Từ mảng Numpy
Tensor có thể được tạo từ mảng NumPy (và ngược lại - xem [Bridge with NumPy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

### Từ một tensor khác
Tensor mới giữ lại các thuộc tính (hình dạng, kiểu dữ liệu) của đối số tensor, trừ khi bị ghi đè.

In [4]:
x_ones = torch.ones_like(x_data) # giữ lại các thuộc tính của x_data 
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # ghi đè kiểu dữ liệu của x_data
print(f"Ones Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Ones Tensor: 
 tensor([[0.7909, 0.9287],
        [0.5137, 0.6068]]) 



### Với các giá trị ngẫu nhiên hoặc không đổi:

`shape` là một bộ kích thước tensor. Trong các hàm bên dưới, nó xác định kích thước của tensor đầu ra.

In [5]:
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.0776, 0.6334, 0.2463],
        [0.3295, 0.7944, 0.8388]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## Các thuộc tính của một Tensor
Thuộc tính tensor mô tả hình dạng, kiểu dữ liệu và thiết bị mà chúng được lưu trữ trên đó.

In [6]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Toán tử (Operations) trên Tensors
Hơn 100 phép toán tensor, bao gồm số học, đại số tuyến tính, thao tác ma trận (chuyển vị ((transposing), lập chỉ mục (indexing), cắt (slicing)), lấy mẫu (sampling) và hơn thế nữa được mô tả toàn diện tại đây.

Mỗi hoạt động này có thể được chạy trên GPU (thường ở tốc độ cao hơn trên CPU). Nếu bạn đang sử dụng Colab, hãy phân bổ GPU bằng cách đi tới **Runtime  > Change runtime type > GPU**.

Theo mặc định, tensor được tạo trên CPU. Chúng ta cần phải di chuyển rõ ràng các tensors sang GPU bằng phương thức .to (sau khi kiểm tra tính khả dụng của GPU). Hãy nhớ rằng việc sao chép các bộ nhớ lớn trên các thiết bị có thể tốn kém về thời gian và bộ nhớ!

In [7]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Hãy thử một số thao tác từ danh sách. Nếu bạn đã quen thuộc với API NumPy, bạn sẽ thấy API Tensor thật dễ sử dụng.
### Lập chỉ mục và cắt giống như numpy tiêu chuẩn:

In [8]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[..., -1])
tensor[:, -1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])
tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])


### Nối các tensor 
Bạn có thể sử dụng `torch.cat` để nối một chuỗi các tensor dọc theo một kích thước nhất định. Xem thêm `torch.stack`, một tensor nối với tensor khác với `torch.cat` một cách tinh tế.

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.]])


### Các phép tính toán học


In [11]:
# Điều này tính toán phép nhân ma trận giữa hai tensor. y1, y2, y3 sẽ có cùng giá trị
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# Điều này tính toán các phần tử. z1, z2, z3 sẽ có cùng giá trị
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

### Các tensor một phần tử 
Nếu bạn có tensor một phần tử, chẳng hạn bằng cách tổng hợp tất cả các giá trị của tensor thành một giá trị, bạn có thể chuyển đổi nó thành một giá trị số Python bằng cách sử dụng `item()`:

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


### Các phép toán tại chỗ (In-place operations)
Các phép toán lưu trữ kết quả vào toán hạng được gọi là tại chỗ. Chúng được biểu thị bằng hậu tố `_`. Ví dụ: `x.copy_ (y)`, `x.t_ ()`, sẽ thay đổi `x`.

In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]]) 

tensor([[6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.],
        [6., 6., 6., 5.]])


# Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
## Tensor to NumPy array

In [14]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


Một sự thay đổi trong tensor phản ánh trong mảng NumPy.

In [15]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [16]:
n= np.ones(5)
t = torch.from_numpy(n)

Những thay đổi trong mảng NumPy phản ánh trong tensor.

In [17]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
